### ISSUE TITLE
ValueError: simplify() takes from 1 to 4 positional arguments but 7 were given

### ISSUE THREAD

**Issue by ProgVal** [ProjetPP/PPP-CAS#11]
From the logs:

```
Traceback (most recent call last):
  File "/home/ppp/.local/lib/python3.4/site-packages/ppp_libmodule/http.py", line 97, in on_post
    return self.process_request(request)
  File "/home/ppp/.local/lib/python3.4/site-packages/ppp_libmodule/http.py", line 86, in process_request
    answers = self.router_class(request).answer()
  File "/home/ppp/.local/lib/python3.4/site-packages/ppp_cas/requesthandler.py", line 28, in answer
    outputString, outputLatex=evaluate(self.tree.value)
  File "/home/ppp/.local/lib/python3.4/site-packages/ppp_cas/evaluator.py", line 25, in evaluate
    expr, latex = process(eval_input, inputFormula, timeout=Config().timeout, heap_size=Config().max_heap)
  File "/home/ppp/.local/lib/python3.4/site-packages/ppp_cas/supyprocess.py", line 83, in process
    raise v
ValueError: simplify() takes from 1 to 4 positional arguments but 7 were given
```

I have no idea what the request was.

**Comment by s-i-newton** [comment]
On which entry?

And that does not happen anymore.
Le 19/01/2015 16:15, Valentin Lorentz a écrit :
>
> From the logs:
>
> |Traceback (most recent call last):
>    File "/home/ppp/.local/lib/python3.4/site-packages/ppp_libmodule/http.py", line 97, in on_post
>      return self.process_request(request)
>    File "/home/ppp/.local/lib/python3.4/site-packages/ppp_libmodule/http.py", line 86, in process_request
>      answers = self.router_class(request).answer()
>    File "/home/ppp/.local/lib/python3.4/site-packages/ppp_cas/requesthandler.py", line 28, in answer
>      outputString, outputLatex=evaluate(self.tree.value)
>    File "/home/ppp/.local/lib/python3.4/site-packages/ppp_cas/evaluator.py", line 25, in evaluate
>      expr, latex = process(eval_input, inputFormula, timeout=Config().timeout, heap_size=Config().max_heap)
>    File "/home/ppp/.local/lib/python3.4/site-packages/ppp_cas/supyprocess.py", line 83, in process
>      raise v
> ValueError: simplify() takes from 1 to 4 positional arguments but 7 were given
> |
>
> I have no idea what the request was.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ProjetPP/PPP-CAS/issues/11>.
>

-- 

Marc CHEVALIER
