### ISSUE TITLE
Integrate[Sin[x*y], {x, 0, 1}, {y, 0, x}] is broken

### ISSUE THREAD

**Issue by Ezibenroc** [ProjetPP/PPP-CAS#19]
[Integrate[Sin[x*y], {x, 0, 1}, {y, 0, x}]](http://askplatyp.us/?lang=en&q=Integrate%5BSin%5Bx*y%5D%2C+%7Bx%2C+0%2C+1%7D%2C+%7By%2C+0%2C+x%7D%5D+)

**Comment by s-i-newton** [comment]
This integration is in my tests (https://github.com/ProjetPP/PPP-CAS/blob/master/tests/testRequestHandler.py#L69) and you can see that everything's going well (https://travis-ci.org/ProjetPP/PPP-CAS) => not my fault. 

But if Angel is used by @Tpt to update his entity store, or anythng else, maybe it  need more time.

**Comment by s-i-newton** [comment]
Timeout!

**Comment by Ezibenroc** [comment]
What is the value of the timeout?

**Comment by Tpt** [comment]
10 seconds

**Comment by Ezibenroc** [comment]
This question is in the examples we give, so we need to do something: either remove the question, or fix it.
Not sure it would be good to give a higher timeout, 10 seconds is already huge.

**Comment by s-i-newton** [comment]
I remove this question from the example list and maybe, in the futur, we will have a more powerfull server...
