### ISSUE TITLE
Support \left and \right

### ISSUE THREAD

**Issue by Ezibenroc** [ProjetPP/PPP-CAS#20]
It would be nice if queries like [2*\left(1+3\right)](http://askplatyp.us/?lang=en&q=2*%5Cleft(1%2B3%5Cright)) worked. It would allow to copy paste some latex code directly, without having to remove by hand `\left` and `\right`.

**Comment by s-i-newton** [comment]
That's odd : https://github.com/ProjetPP/PPP-CAS/blob/master/ppp_cas/latexPreprocessing.py#L66 ...

**Comment by s-i-newton** [comment]
I think your query is not interpreted as LaTeX. I juste have to make \left and \right caracteristic.

**Comment by Ezibenroc** [comment]
Is the backslash used in the other syntaxes? If not, you could use it as caracteristic.

**Comment by s-i-newton** [comment]
And I have some test for this : https://github.com/ProjetPP/PPP-CAS/blob/5f2a87c6ef20a011624a200c3ca7573f13ece7c1/tests/testLatexPreprocessing.py#L26

And indeed, it is just a problem in the LaTeX distinguisher (http://askplatyp.us/?lang=en&q=\sqrt{2*\left%281%2B3\right%29})

In fact, every mathematical formula has a meaning in LaTeX but not necessary the same, so, I cannot consider everything as LaTeX. For instance, 2^42 = 2^(42) for every CAS but (2^4)*2 for LaTeX.

**Comment by s-i-newton** [comment]
Double fix in 281e50d0fb8b6e13b119addd17bc87c969fd48de.
