### ISSUE TITLE
Support \times

### ISSUE THREAD

**Issue by Ezibenroc** [ProjetPP/PPP-CAS#21]
It would be nice if queries like [2\times(1+3))](http://askplatyp.us/?lang=en&q=2%5Ctimes(1%2B3)) worked. It would allow to copy paste some latex code directly, without having to transform by hand `\times` into `*`.

**Comment by s-i-newton** [comment]
Yes that's a problem and will be fixed soon. I think, for the idea of unhandled function or notation, a topic in http://discourse.askplatyp.us/ is more convenient.

**Comment by s-i-newton** [comment]
Double fix in commit 281e50d0fb8b6e13b119addd17bc87c969fd48de.
