### ISSUE TITLE
N[1- Sum[Binomial[10,k] * 0.2^k *0.8^(10-k), {k, 0, 3}]] should work

### ISSUE THREAD

**Issue by Tpt** [ProjetPP/PPP-CAS#22]
http://askplatyp.us/?lang=fr&q=N[1-+Sum[Binomial[10%2Ck]+*+0.2^k+*0.8^%2810-k%29%2C+{k%2C+0%2C+3}]]

**Comment by s-i-newton** [comment]
That is odd. That works perfectly on the last version in master. I 
assume that the deployed version is a bit too old. It will be fix at the 
next deployment.

**Comment by ProgVal** [comment]
Deployed.

**Comment by s-i-newton** [comment]
Yay!
