### ISSUE TITLE
CAS does not always answer

### ISSUE THREAD

**Issue by Ezibenroc** [ProjetPP/PPP-CAS#23]
[2+3](http://askplatyp.us/?lang=en&q=2%2B3) sometimes gives the good result, but sometimes does not answer.
Not sure if the problem comes from the CAS or from something else.

**Comment by s-i-newton** [comment]
I already observed that. By clicking several times, the answer finally 
comes. The CAS is deterministic (in particular to determine if an input 
is math), so the problem is somewhere else.

**Comment by ProgVal** [comment]
Fixed. It looks like one of the workers crashed.
