### ISSUE TITLE
Add compatibility with Sympy 1.0

### ISSUE THREAD

**Issue by Tpt** [ProjetPP/PPP-CAS#25]
See: https://github.com/sympy/sympy/wiki/Release-Notes-for-1.0
And failing tests: https://travis-ci.org/ProjetPP/PPP-CAS/jobs/92423368

**Comment by marc-chevalier** [comment]
Fixed by 01ba7d2e0c0c9f15d8d6ebc099ad1c343c5666b0 and 614f0197e7d1194cfab19e9284bd2174393504ed
Sympy change the LaTeX printing at each version...
